### PR TITLE
Implementation using RxJava2

### PR DESCRIPTION
**Pull request by miszmaniac**
I needed version for RxJava of your library.

There is one difference tho, you'll get ClassCastException while trying to save wrong value inside already subscribed observe.

### CODE REVIEW

**Comment by pakoito** [comment]
I like the idea, but the library can't stop working for RxJava 1. I'll try a different approach and implement your changes with it.

May I ask, why did you change the internal subjects to Relays?

**Comment by miszmaniac** [comment]
Hmm... good question about Relay, my thought was to prevent Terminal events, but I've just prepared the library, and I'll use it in project in next days, so maybe that was premature.

All tests pass with regular Subject, so I've removed relay.

**Comment by miszmaniac** [comment]
Maybe just put a link to my fork in Readme for future users.

**Comment by pakoito** [comment]
I'm going to create a new repository for the project, and I can merge your changes there. There's one or two changes I want to add to your implementation.

**Comment by miszmaniac** [comment]
Question... why didn't you use BehaviorSubject for observe method?
When I started to implement storages inside my APP i often need last known data synchronously, and it would be easier to just use observe().first() ?

**Comment by pakoito** [comment]
In the design, Observe only returns changes to the model and not its value. This way you're not tied to anyone's opinions on what the initial value should be and you can still implement this behaviour yourself.

**Comment by pakoito** [comment]
I have a couple of presentations coming up, and I can't plan to do the port at least until the third week of February.

**Comment by pakoito** [comment]
As promised, the port is complete: https://github.com/pakoito/RxPaper2

Check the release notes for changes: https://github.com/pakoito/RxPaper2/releases/tag/1.0.0

**Pull request closed without merging**
